IF DB_ID('EcoStemDB') IS NULL
BEGIN
  CREATE DATABASE EcoStemDB;
END;
GO

USE EcoStemDB;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'app')
BEGIN
  EXEC('CREATE SCHEMA app');
END;
GO

CREATE TABLE app.Users (
  UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  FirstName NVARCHAR(120) NOT NULL,
  LastName NVARCHAR(120) NULL,
  Email NVARCHAR(190) NULL,
  Phone NVARCHAR(40) NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  PlanStatus NVARCHAR(30) NOT NULL DEFAULT 'free',
  IsEmailVerified BIT NOT NULL DEFAULT 0,
  IsPhoneVerified BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_Users_Email UNIQUE (Email),
  CONSTRAINT UQ_Users_Phone UNIQUE (Phone)
);
GO

CREATE TABLE app.Sessions (
  SessionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  UserAgent NVARCHAR(400) NULL,
  IpAddress NVARCHAR(64) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ExpiresAt DATETIME2 NULL,
  RevokedAt DATETIME2 NULL,
  CONSTRAINT FK_Sessions_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE app.Plants (
  PlantId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  PlantName NVARCHAR(150) NOT NULL,
  SpeciesName NVARCHAR(180) NULL,
  ScientificName NVARCHAR(220) NULL,
  Notes NVARCHAR(1000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Plants_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE app.Subscriptions (
  SubscriptionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  PlanCode NVARCHAR(50) NOT NULL,
  PlanName NVARCHAR(120) NOT NULL,
  Status NVARCHAR(30) NOT NULL,
  StartDate DATETIME2 NOT NULL,
  EndDate DATETIME2 NOT NULL,
  AutoRenew BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Subscriptions_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE app.Payments (
  PaymentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  SubscriptionId UNIQUEIDENTIFIER NULL,
  Amount DECIMAL(12,2) NOT NULL,
  CurrencyCode CHAR(3) NOT NULL DEFAULT 'USD',
  PaymentMethod NVARCHAR(40) NOT NULL,
  ProviderName NVARCHAR(80) NULL,
  ProviderReference NVARCHAR(120) NULL,
  MaskedCard NVARCHAR(30) NULL,
  Status NVARCHAR(40) NOT NULL,
  PaidAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Payments_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId),
  CONSTRAINT FK_Payments_Subscriptions FOREIGN KEY (SubscriptionId) REFERENCES app.Subscriptions(SubscriptionId)
);
GO

CREATE TABLE app.Analyses (
  AnalysisId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NULL,
  PlantId UNIQUEIDENTIFIER NULL,
  SourceType NVARCHAR(40) NOT NULL,
  Severity NVARCHAR(30) NOT NULL,
  Confidence DECIMAL(5,2) NULL,
  Summary NVARCHAR(MAX) NOT NULL,
  LocationLatitude DECIMAL(10,7) NULL,
  LocationLongitude DECIMAL(10,7) NULL,
  TerrainDescription NVARCHAR(250) NULL,
  SensorMoisture DECIMAL(5,2) NULL,
  SensorTemperature DECIMAL(5,2) NULL,
  SensorLight DECIMAL(5,2) NULL,
  SoilPh DECIMAL(4,2) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Analyses_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId),
  CONSTRAINT FK_Analyses_Plants FOREIGN KEY (PlantId) REFERENCES app.Plants(PlantId)
);
GO

CREATE TABLE app.AnalysisImages (
  AnalysisImageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  AnalysisId UNIQUEIDENTIFIER NOT NULL,
  FileName NVARCHAR(255) NOT NULL,
  MimeType NVARCHAR(100) NULL,
  FileUrl NVARCHAR(500) NULL,
  SortOrder INT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_AnalysisImages_Analyses FOREIGN KEY (AnalysisId) REFERENCES app.Analyses(AnalysisId)
);
GO

CREATE TABLE app.IoTReadings (
  ReadingId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NULL,
  PlantId UNIQUEIDENTIFIER NULL,
  DeviceCode NVARCHAR(80) NULL,
  Latitude DECIMAL(10,7) NULL,
  Longitude DECIMAL(10,7) NULL,
  SoilMoisture DECIMAL(5,2) NULL,
  TemperatureC DECIMAL(5,2) NULL,
  LightPercent DECIMAL(5,2) NULL,
  SoilPh DECIMAL(4,2) NULL,
  HumidityPercent DECIMAL(5,2) NULL,
  RecordedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_IoTReadings_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId),
  CONSTRAINT FK_IoTReadings_Plants FOREIGN KEY (PlantId) REFERENCES app.Plants(PlantId)
);
GO

CREATE TABLE app.ContactMessages (
  MessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NULL,
  FullName NVARCHAR(180) NOT NULL,
  Email NVARCHAR(190) NOT NULL,
  Subject NVARCHAR(180) NOT NULL,
  MessageBody NVARCHAR(MAX) NOT NULL,
  WhatsAppSent BIT NOT NULL DEFAULT 0,
  EmailSent BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_ContactMessages_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE app.CookieConsents (
  ConsentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NULL,
  ConsentType NVARCHAR(50) NOT NULL,
  ConsentValue NVARCHAR(30) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_CookieConsents_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE app.Notifications (
  NotificationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NULL,
  Channel NVARCHAR(30) NOT NULL,
  TargetAddress NVARCHAR(190) NOT NULL,
  Subject NVARCHAR(250) NULL,
  MessageBody NVARCHAR(MAX) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'queued',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  SentAt DATETIME2 NULL,
  CONSTRAINT FK_Notifications_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId)
);
GO

CREATE INDEX IX_Analyses_UserId_CreatedAt ON app.Analyses(UserId, CreatedAt DESC);
CREATE INDEX IX_Payments_UserId_CreatedAt ON app.Payments(UserId, CreatedAt DESC);
CREATE INDEX IX_IoTReadings_PlantId_RecordedAt ON app.IoTReadings(PlantId, RecordedAt DESC);
GO
